# Generated by Django 5.1.3 on 2024-11-24 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='authors',
            field=models.ManyToManyField(related_name='books', to='myapp.author'),
        ),
        migrations.DeleteModel(
            name='Compound',
        ),
    ]
