"""
Django settings for python3 project.

Generated by 'django-admin startproject' using Django 4.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""





















import os
from pathlib import Path
from dotenv import load_dotenv

# Определение базового каталога проекта
BASE_DIR = Path(__file__).resolve().parent.parent

# Загрузка переменных окружения из .env файла
load_dotenv(os.path.join(BASE_DIR, '.env'))
SECRET_KEY = os.getenv('SECRET_KEY', 'default_secret_key')  # Замените 'default_secret_key' на ваш секретный ключ
DEBUG = os.getenv('DEBUG', 'True') == 'True'

# Разрешённые хосты
ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1').split(',')

# Приложения
INSTALLED_APPS = [
    # ... другие приложения ...
    'storages',  # Добавляем django-storages
    'myapp',      # Замените на название вашего приложения
]

# Настройки для Yandex Object Storage (S3-совместимое)
AWS_ACCESS_KEY_ID = os.getenv('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.getenv('AWS_SECRET_ACCESS_KEY')
AWS_STORAGE_BUCKET_NAME = 'bookss'  # Ваш бакет
AWS_S3_ENDPOINT_URL = 'https://storage.yandexcloud.net'
AWS_S3_REGION_NAME = 'ru-central1'
AWS_S3_SIGNATURE_VERSION = 's3v4'
AWS_S3_ADDRESSING_STYLE = 'path'
AWS_DEFAULT_ACL = 'public-read'

# Настройки статики и медиа-файлов
STATICFILES_STORAGE = 'myapp.storage_backends.StaticStorage'
DEFAULT_FILE_STORAGE = 'myapp.storage_backends.MediaStorage'

STATIC_URL = f'https://{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/static/'
MEDIA_URL = f'https://{AWS_S3_ENDPOINT_URL}/{AWS_STORAGE_BUCKET_NAME}/media/'




STATIC_ROOT = BASE_DIR / "staticfiles"





import os  # Убедитесь, что модуль os импортирован

# Добавьте эти строки в конце файла settings.py или в соответствующем разделе

MEDIA_URL = '/media/'  # URL для доступа к медиафайлам
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')






# Остальные настройки Django...

# SECURITY WARNING: keep the secret key used in production secret!
ACCESS_KEY = 'YCAJEBroZohgmETsUhiJ5zTFs'
SECRET_KEY = 'YCOxfenUj9v-OQRby-7cQzlR8UICOWqsa65Gl5-N'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

AWS_ACCESS_KEY_ID = 'YCAJEBroZohgmETsUhiJ5zTFs'
AWS_SECRET_ACCESS_KEY = 'YCOxfenUj9v-OQRby-7cQzlR8UICOWqsa65Gl5-N'
AWS_S3_REGION_NAME = 'ru-central1'
# Дополнительные параметры (опционально)
AWS_DEFAULT_ACL = 'public-read'  # Или другой, в зависимости от требований
AWS_QUERYSTRING_AUTH = False

REST_FRAMEWORK = {
    'DEFAULT_RENDERER_CLASSES': [
        'rest_framework.renderers.JSONRenderer',  # Рендеринг данных в JSON
    ],
}














ALLOWED_HOSTS = [
    'localhost',
    '127.0.0.1',
    # Добавьте ваш домен или IP-адрес сервера
    'your-domain.com',
    'www.your-domain.com',
]


# Application definition

INSTALLED_APPS = [
'django_extensions',
    'storages',
    'myapp',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'python3.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'python3.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME':'mydatabase',
        'USER':'myuser',
        'PASSWORD':'mypassword',
        'HOST':'localhost',
        'PORT':'5432',

    }
}


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


BASE_DIR = Path(__file__).resolve().parent.parent

# Настройки статических файлов
STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Настройки для хранения статических файлов в Yandex Object Storage
STATICFILES_STORAGE = 'storages.backends.s3boto3.S3Boto3Storage'

